### ISSUE TITLE
Annotation Printing

### ISSUE THREAD

**Issue by jadhavajay** [instructure/pdf-annotate.js#22]
Hello,

Great work done by @mzabriskie, @aaronshaf and team.

I just looked at the documentation but couldn't find anything about printing the annotations. Is there a way to print the annotations along with the PDF itself?

**Comment by jadhavajay** [comment]
@mzabriskie @aaronshaf Can you please put some light on this? May be a pointer to some docs will be useful.

**Comment by benjaminwols** [comment]
@jadhavajay Did you find a way to implement annotation printing?

**Comment by jadhavajay** [comment]
@benjaminwols Not yet. I moved on to some other tasks in my project due to lack of documentation and support. I may probably come back to it in next month to do some more digging of code to figure out a solution.

**Comment by aaronshaf** [comment]
We are reworking this library to be React components. It's not in the open for now. We will revisit open sourcing it in a few months.

**Comment by jadhavajay** [comment]
@aaronshaf Thanks for the update. I was still curious to know if there is any way of printing annotations in the current release?

**Comment by aaronshaf** [comment]
No, you'd need to merge the annotations into the PDF. You can use something like PDFBox for that.
