### ISSUE TITLE
Error: PDFJS.DefaultTextLayerFactory is not a constructor

### ISSUE THREAD

**Issue by zeinebM** [instructure/pdf-annotate.js#33]
Hi, 
I'm trying pdf-annotate for an Angular 2 application.
I'm getting an error when executing ` UI.renderPage(1, RENDER_OPTIONS)` with these options : 

`const RENDER_OPTIONS = {
      documentId: this.url,
      pdfDocument: null,
      scale: 1,
      rotate: 0
    };`

PDF URL is : `url = '../../assets/ressources/testPDF2.pdf';`

And using local storage for test purposes `PDFJSAnnotate.setStoreAdapter(new PDFJSAnnotate.LocalStoreAdapter());`

`EXCEPTION: Uncaught (in promise): TypeError: PDFJS.DefaultTextLayerFactory is not a constructor`.

Any help would be appreciated. Thanks !

**Comment by neilsimp1** [comment]
I was having this issue too. Make sure `shared/pdf_viewer.js` is included in your html before `pdf-annotate.js`. It's in the viewer that DefaultTextLayerFactory gets added to PDFJS.
