### ISSUE TITLE
How to Download annotate PDF ?

### ISSUE THREAD

**Issue by rmemon** [instructure/pdf-annotate.js#40]
After adding certain annotation, how to download annotate pdf, 
Thanks in advance

**Comment by KaneMorgan** [comment]
So the library doesn't actually create an annotated pdf file. It works by putting an overlay on top of the rendered pdf with the annotations.

The annotations are just stored in JSON in the browsers local storage, if you want to use them elsewhere you might be able to implement a store adapter to get the JSON out but you'd probably still need this library to render them

**Comment by fdbatista** [comment]
In my case, I save annotations in database. I have a controller action for download which reads original pdf file using fpdi, retrieves annotations from database, inserts them into pdf using tcpdf and finally returns the new annotated pdf also with tcpdf.

**Comment by rmemon** [comment]
Hi @fdbatista thank you, I did it using same rule, only difference i have not use tcpdf or fpdi, I build my own custom code written  in node, Please find the URL, draw some annotation and press on download button.

[https://pdf-annotate.herokuapp.com/](https://pdf-annotate.herokuapp.com/)

I will also look to try for fpdi and tcpdf in my free time, Thanks

**Comment by manzarlove** [comment]
Hi @rmemon  I am working on PHP and i am making pdf annotation.  Could you tell me How to integrate  Download button my PDF annotation in php without using tcpdf or fpdi.

**Comment by RameshSenagasetti** [comment]
Hi @rmemon  thank you,  can you help me out in doing the download the annotated PDF using node stuff as I am struggling with same issue.

**Comment by jadhavajay** [comment]
I have built my custom code on the back-end using C#.NET which parses the JSON annotations and creates those annotations in PDF.

However, I am facing issues with coordinates positions with some annotations such as 'drawing'

**Comment by Mariachi1231** [comment]
Hi @jadhavajay, can share your code?

**Comment by gaganmurghai** [comment]
@fdbatista 
I am new with this and trying to create pdf with saved annotations in database.
When I am trying to use stored annotations from database, the location of those annotation are not on same position with x and y coordinates of PDF. Can you please help me out with this.

**Comment by fdbatista** [comment]
Hi, @gaganmurghai.

That might be a problem with the measure unit you're using. When you instantiate the FPDI object, you must pass a parameter that specifies the measurement unit, like this:

$pdf = new FPDI('', 'pt', 'A4', true, 'UTF-8', false, false);

If I'm not wrong, because I haven't touched this code in a while, the 2nd parameter stands for Points. There are also pixels, millimeters and so one, but Points work for me.

Happy coding.

**Comment by gaganmurghai** [comment]
@fdbatista Can you please share some code for that. It will be really help full for me.

**Comment by fdbatista** [comment]
I already did.
Here you instantiate the FPDI object and insert comments loaded from a database via an api request.
In my case, I use PHP for building the RESTful API. This depends on your own business logic.
------------------------------------------------------------
$pdf = new FPDI('', 'pt', 'A4', true, 'UTF-8', false, false);

try {
    $file_name = "Test.pdf";
    $annotations_url = "http://my-server/api/annotations?document_id=$file_name";  //this is my API function
    $annotations = file_get_contents($annotations_url);
    $json = NULL;
    if ($annotations) {
        $json = json_decode(json_decode($annotations));
    }
    $pageCount = $pdf->setSourceFile("../../items/$id/$file_name");
    for ($i = 1; $i <= $pageCount; $i++) {
        $tplIdx = $pdf->importPage($i, '/MediaBox');
        $pdf->AddPage();
        if ($json) {
            foreach ($json as $annotation) {
                $pdf->Annotation($curr_annotation->x, $curr_annotation->y, 100, 70, $annotation[1]->content, ['Subtype' => 'Text', 'Name' => 'Comment', 'C' => array(255, 255, 0)]);
            }
        }
        $pdf->useTemplate($tplIdx);
    }
    $pdf->Output($file_name, 'D');
} catch (Exception $exc) {
    $pdf->AddPage();
    $pdf->Text(200, 200, $exc->getMessage());
    $pdf->Output('Exception', 'D');
}

**Comment by gaganmurghai** [comment]
@fdbatista thanks. Let me try and I will get back to you. Again thank you very much.

**Comment by gaganmurghai** [comment]
@fdbatista Can I use image instead of text annotation. Actually I have tired Image for this 

> $pdf->Image('images/image_demo.jpg', 15, 140, 75, 113, 'JPG', 'http://www.tcpdf.org', '', true, 150, '', false, false, 1, false, false, false);

But when I am passing x and y coordinates it changes the position. Have you any Idea for that. And also I want to add image on particular page. When I was trying previous code it parse the image on all the pages. Please me know if you have any idea for the same

**Comment by fdbatista** [comment]
About the position, try changing the unit, as I said previously. 
And this method allows you to add a new page to work on it:

$pdf->AddPage();

**Comment by gaganmurghai** [comment]
thanks @fdbatista I will try it.

**Comment by gaganmurghai** [comment]
@rmemon @fdbatista @KaneMorgan Hello guys, I am looking for alternate of fpdi and tcpdf in node js. Actually I have built the functionality to download Pdf with annotations in php but now as per my requirements I need this in node Js.
Please help me out in this.

**Comment by gaganmurghai** [comment]
@rmemon thanks, I will try this one.

**Comment by gaganmurghai** [comment]
@Vishnupriya112 @rmemon I need that too.

**Comment by rmemon** [comment]
Hi

Sharing code to draw Circle, at position X:400, Y: 400, radius: 30 , page: 1

```
var resultPath  = PATH_TO_RESULT_FILE,    
     sourcePath = PATH_TO_SOURCE_FILE,
     logFilePath = PATH_TO_LOG_FILE;

var hummus = require('hummus');
var pdfWriter = hummus.createWriterToModify(sourcePath, {
    modifiedFilePath: resultPath,
    log: logFilePath
});

var pageModifier = new hummus.PDFPageModifier(pdfWriter, 0, true);
var cxt = pageModifier.startContext().getContext();

cxt.drawCircle(400, 400, 30, {
    type: 'fill',
    color: 'red',
});

pageModifier.endContext().writePage();
pdfWriter.end();
```
Let me know in a case of any concerns.

**Comment by aathirag** [comment]
document.createElementNS('http://www.w3.org/2000/svg', 'rect'); Why we are using this link http://www.w3.org/2000/svg?

**Comment by aathirag** [comment]
UI.addEventListener('annotation:click', handleAnnotationClick); is not calling handleAnnotationClick function ? Am I missing anything to add

**Comment by BharatDevda** [comment]
Hi @rmemon 

Please provide some valuable solution for below issue.

1. Messy content in pdf after second page. (Already i was Tried #57 ) 
2.Helpful hints for Download Pdf with annotation.

Thanks in advance.

**Comment by aathirag** [comment]
I have tried this because of annotaion size is big Request Aborted is shows.How can I overcome this issue

**Comment by gaganmurghai** [comment]
Helli @rmemon as you mention in above code "I am Sharing code to draw Circle, at position X:400, Y: 400, radius: 30 , page: 1".

I am not able to found the page that where I need to add this parameter in code i.e page number.

Please suggest me.

Thanks

**Comment by rmemon** [comment]
Hi @gaganmurghai 

Please provide your page number parameter here,

`var pageModifier = new hummus.PDFPageModifier(pdfWriter,page_number,true);    // page_number [0,1,2,3....,]`

**Comment by gaganmurghai** [comment]
Thanks a lot @rmemon

**Comment by rmemon** [comment]
@gaganmurghai  Can share PDF ??

**Comment by gaganmurghai** [comment]
@rmemon thanks there was issue with pdf. 

Now I am trying to Place image on pdf and I am passing the x,y coordinates  on in code but its not showing the image on appropriate place. Can you have any idea. I think there is a issue with measurement unit.
Thanks again.

**Comment by aathirag** [comment]
[101100_hbs (1)_1.pdf](https://github.com/instructure/pdf-annotate.js/files/2008155/101100_hbs.1._1.pdf)

**Comment by rmemon** [comment]
@aathirag  Thanks i will look for this pdf, shortly.

**Comment by gaganmurghai** [comment]
@rmemonI want to add multiple images on multiple pages. But only able to add one image  at a time. Please help me out in this.

Here is my sample code.

` var resultPath = "./downloads/" + pdfkey,
     sourcePath = "./downloads/" + pdfkey,
     logFilePath = "/var/www/html/lowrate-latest/lowrate/backend/LowRate_API/log.text";

 var hummus = require('hummus');
 var pdfWriter = hummus.createWriterToModify(sourcePath, {
     modifiedFilePath: resultPath,
     log: logFilePath
 });


 var itemsProcessedDone = 0;
 var itemsProcessed = 0;
 var itemsProcessedNext = 0;
 var cxt;
 var pageModifier;



 AnnotaionObj.forEach(element => {

     var pageNumber = element.pageNumber - 1;
     pageNumber = parseInt(pageNumber);
     console.log(pageNumber + " pageNumber");
     var pageModifier = new hummus.PDFPageModifier(pdfWriter, pageNumber, true);
     var cxt = pageModifier.startContext().getContext();

     if (element.ImageUrl != "" && element.ImageUrl != undefined) {



         //getting file name 
         let filenameary = element.ImageUrl.split('/');
         let path = "./downloads/" + filenameary[3];
         cxt.drawImage(element.x, element.y, path, {
             transformation: {
                 width: 100,
                 height: 40,
                 proportional: false
             }
         });
         cxt.drawImage(element.x, element.y, "./downloads/1526472073_initials.png", {
             transformation: {
                 width: 100,
                 height: 40,
                 proportional: false
             }
         });


     }
     pageModifier.endContext().writePage();

     itemsProcessed++;
     if (itemsProcessed === AnnotaionObj.length) {
         pdfWriter.end();

     }


 });`

**Comment by aathirag** [comment]
In the above code, you are always modifying the source path. Which does not contain any annotation.
So 

var pdfWriter = hummus.createWriterToModify(sourcePath, {
      modifiedFilePath: resultPath,
      log: logFilePath
  });
 pdfWriter.end();



AnnotaionObj.forEach(element => 
{
  var pdfWriter = hummus.createWriterToModify(resultPath);
   var pageNumber = element.pageNumber - 1;
   pageNumber = parseInt(pageNumber);
   console.log(pageNumber + " pageNumber");
   var pageModifier = new hummus.PDFPageModifier(pdfWriter, pageNumber, true);
   var cxt = pageModifier.startContext().getContext();

   if (element.ImageUrl != "" && element.ImageUrl != undefined) {

     //getting file name 
     let filenameary = element.ImageUrl.split('/');
     let path = "./downloads/" + filenameary[3];
     cxt.drawImage(element.x, element.y, path, {
         transformation: {
             width: 100,
             height: 40,
             proportional: false
         }
     });
   
   }
   pageModifier.endContext().writePage();

   itemsProcessed++;
   if (itemsProcessed === AnnotaionObj.length) {
     pdfWriter.end();

   }


});`

**Comment by aathirag** [comment]
how are you writing text content? for me, it's not opening in Adobe Reader. Can you please share your code. Here is my code

 ```
cxt.writeText(
                    "content",
                    x,y,
                    {font:pdfWriter.getFontForFile('./public/fonts/Roboto-Bold.ttf'),size:14,colorspace:'rgb',color:'red'}
                    );

```

**Comment by edsontrick** [comment]
@aathirag have you got it ?

**Comment by syedali78666** [comment]
@rmemon
How can I add a circle, arrow annotation like a rectangle one? You have made circles but they are not resizable. and also I want to add custom fonts for TEXT TOOL.

**Comment by junaidlodhi7** [comment]
> Hi @fdbatista thank you, I did it using same rule, only difference i have not use tcpdf or fpdi, I build my own custom code written in node, Please find the URL, draw some annotation and press on download button.
> 
> https://pdf-annotate.herokuapp.com/
> 
> I will also look to try for fpdi and tcpdf in my free time, Thanks

hi Can you please make a public repo of this project so I can also use it???

**Comment by Vishnupriya112** [comment]
@rmemon  I can able to download the pdf with annotation. But In Adobe reader am getting error
![adobeerror](https://user-images.githubusercontent.com/38549946/50273151-dbf23a80-045f-11e9-8cc6-dac72f7eb95b.png)
