### ISSUE TITLE
PDF file gets displayed incorrectly 

### ISSUE THREAD

**Issue by fdbatista** [instructure/pdf-annotate.js#45]
Hi.

I've just cloned and installed via npm the application and I faced this issue within /scripts/web when trying to start the application (https://github.com/instructure/pdf-annotate.js/issues/24) running on Windows 10 OS. I solved it according to the explanation, but don't know if that has something to do with my current problem.

The fact is that when I start the application, the first page of the pdf gets displayed correctly, but the other ones become a mess of overlaid layers.

Can anyone provide some clue about what might be happening here?

![page_01_ok](https://user-images.githubusercontent.com/11459171/29084275-74787b08-7c39-11e7-9663-b6069325c713.png)
![page_02_not_ok](https://user-images.githubusercontent.com/11459171/29084326-a940e4a6-7c39-11e7-90a0-03fa01670075.jpg)

**Comment by KaneMorgan** [comment]
Take a look at this
https://github.com/DynamicEnvironmentSystems/pdf-annotate.js/pull/7

**Comment by hemant6263** [comment]
i am also facing this same issue tried downloading your project @KaneMorgan but not getting any result

**Comment by AP-Nothize** [comment]
Fixed in #57
