### ISSUE TITLE
Is there more examples of how to use pdf-annotate.js?

### ISSUE THREAD

**Issue by Anandks1993** [instructure/pdf-annotate.js#72]
Sorry that I had to open this as an issue. Since the link to see more example is broken, I couldn't find other examples easily over the internet. So if anyone has or knows simple example of how to use pdf-annotate.js in our project please let me know. Thanks in advance.

**Comment by rogercorrea** [comment]
Hi,

In the top bar of home page has the link to the example:
http://instructure.github.io/pdf-annotate.js/

You also can clone the repo and run the "index.html" file of docs folder.

**Comment by syedali78666** [comment]
an example is working fine. I also opened index.html with a browser, and it only shows toolbar, not any pdf. I don't know how to open my pdf with annotation toolbar.
I added my pdf in web folder and it only working like a pdf viewer as pdf.js do.
How can I use pdf-annotation toolbar with my pdf there is no instructions for that.

**Comment by Anandks1993** [comment]
Thank you @rogercorrea
