### ISSUE TITLE
I updated pdf.js in my project and he work for me now

### ISSUE THREAD

**Issue by rogercorrea** [instructure/pdf-annotate.js#78]
Hi,

I got it updated the code to work with a new pdf.js version.
I also fixed problems as PDF render and HTML5 canvas error.

As I can update the code for help another developers?

**Comment by jcjeancarloo** [comment]
Yes, please!

**Comment by FurloSK** [comment]
@rogercorrea that's great, could you please do that? Either make a pull request, or maybe publish your code under your account? I am dealing with the same problems right now…

**Comment by irrg** [comment]
@rogercorrea could you post your fixes somewhere? Share your fork?

**Comment by DomenicRoti** [comment]
@rogercorrea - I think I'm running into the same issues, could you please share your updates?

**Comment by rogercorrea** [comment]
Yes, sorry for my long time to answer.

Now I can view the PDF file without he has a bad renderer.
In my case, the PDF is in perfectly condition of the view but I can't fix the annotation in iPad / iPhone.

I worked with the repo example (docs folder) and replace file pdf.js and pdf.work.js by the last version that is in Mozilla repo. And also: 

1) I replaced the "PDFJS" variable to "pdfjsLib" (except "PDFJS.DefaultTextLayerFactory()", please don't question me about why);
2) I replaced "pdf.pdfinfo" to "pdf._pdfinfo";
3) I changed the render stuff function with a hack that found here to fix problem caused by canvas render repeat;

I uploaded my example files to the Google Drive to share with you. Please, if anyone can help me a change the repo with "a pretty build", let's go!

https://drive.google.com/file/d/18y89VM7lki0uHlK8JEyGIE-MAzpNS7yA/view?usp=sharing

**Comment by rogercorrea** [comment]
I tried change the pdf.js version in package.json but my NPM don't compiled correcly. I loss hours trying but I couldn't. So I replaced files and contents.

**Comment by rogercorrea** [comment]
I fixed problems and create a new fork with pull request #85 .
